# Generated by Django 6.0.5 on 2026-05-22 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_atencion', models.DateTimeField(verbose_name='Fecha y hora inicio de atención')),
                ('grupo_servicios', models.CharField(choices=[('01', 'Consulta externa'), ('02', 'Apoyo diagnóstico y complementación terapéutica'), ('03', 'Internación'), ('04', 'Quirúrgico'), ('05', 'Atención inmediata')], max_length=2, verbose_name='Grupo de servicios')),
                ('entorno_atencion', models.CharField(choices=[('01', 'Hogar'), ('02', 'Comunitario'), ('03', 'Escolar'), ('04', 'Laboral'), ('05', 'Institucional')], max_length=2, verbose_name='Entorno de atención')),
                ('fecha_triage', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora del triage')),
                ('clasificacion_triage', models.CharField(blank=True, choices=[('01', 'Triage I'), ('02', 'Triage II'), ('03', 'Triage III'), ('04', 'Triage IV'), ('05', 'Triage V')], max_length=2, verbose_name='Clasificación triage')),
                ('tipo_diagnostico_ingreso', models.CharField(choices=[('01', 'Impresión diagnóstica'), ('02', 'Confirmado nuevo'), ('03', 'Confirmado repetido')], max_length=2, verbose_name='Tipo diagnóstico de ingreso')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='catalogos.causaatencion', verbose_name='Causa que motiva la atención')),
                ('diagnostico_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_ingreso', to='catalogos.diagnostico', verbose_name='Diagnóstico principal de ingreso')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='catalogos.modalidadtecnologia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_salud', to='pacientes.paciente')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_atencion', to='catalogos.prestadorsalud', verbose_name='Prestador que realiza la atención')),
                ('via_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='catalogos.viaingreso')),
            ],
            options={
                'verbose_name': 'Contacto con el servicio de salud',
                'verbose_name_plural': 'Contactos con el servicio de salud',
                'db_table': 'ate_contacto_salud',
                'ordering': ['-fecha_inicio_atencion'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resultado', models.DateTimeField(verbose_name='Fecha del resultado')),
                ('valor_resultado', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Valor del resultado observado')),
                ('tipo_diagnostico_egreso', models.CharField(choices=[('01', 'Impresión diagnóstica'), ('02', 'Confirmado nuevo'), ('03', 'Confirmado repetido')], max_length=2)),
                ('fecha_fin_atencion', models.DateTimeField(verbose_name='Fecha y hora fin de atención')),
                ('dias_licencia_maternidad', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Días licencia maternidad')),
                ('condicion_egreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='catalogos.condicionegreso')),
                ('contacto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_valoracion', to='atencion.contactosalud')),
                ('diagnostico_complicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complicaciones', to='catalogos.diagnostico')),
                ('diagnostico_egreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos_principal', to='catalogos.diagnostico', verbose_name='Diagnóstico principal de egreso')),
                ('diagnostico_muerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='causas_muerte', to='catalogos.diagnostico')),
                ('diagnostico_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_relacionados', to='catalogos.diagnostico')),
                ('instrumento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='catalogos.instrumentomedicion')),
                ('parametro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='catalogos.parametroresultado')),
                ('prestador_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_egreso', to='catalogos.prestadorsalud')),
                ('talento_humano_egreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egresos_realizados', to='catalogos.talentohumano')),
            ],
            options={
                'verbose_name': 'Resultado de valoración',
                'verbose_name_plural': 'Resultados de valoración',
                'db_table': 'ate_resultado_valoracion',
                'ordering': ['-fecha_resultado'],
            },
        ),
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(choices=[('01', 'Nueva'), ('02', 'Prórroga')], max_length=2)),
                ('dias', models.PositiveSmallIntegerField(verbose_name='Días de incapacidad')),
                ('resultado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incapacidad', to='atencion.resultadovaloracion')),
            ],
            options={
                'verbose_name': 'Incapacidad',
                'verbose_name_plural': 'Incapacidades',
                'db_table': 'ate_incapacidad',
                'ordering': ['-dias'],
            },
        ),
        migrations.CreateModel(
            name='FactorRiesgoExposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_factor', models.CharField(choices=[('01', 'Químicos'), ('02', 'Físicos'), ('03', 'Biomecánicos'), ('04', 'Psicosociales'), ('05', 'Biológicos')], max_length=2)),
                ('nombre_factor', models.CharField(max_length=250, verbose_name='Nombre del factor de riesgo')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factores_riesgo', to='atencion.resultadovaloracion')),
            ],
            options={
                'verbose_name': 'Exposición a factor de riesgo',
                'verbose_name_plural': 'Exposiciones a factores de riesgo',
                'db_table': 'ate_factor_riesgo',
                'ordering': ['tipo_factor'],
            },
        ),
        migrations.CreateModel(
            name='AntecedenteSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alergia', models.CharField(blank=True, choices=[('01', 'Medicamento'), ('02', 'Alimento'), ('03', 'Sustancia del ambiente'), ('04', 'Sustancia que entra en contacto con la piel'), ('05', 'Picadura de insectos')], max_length=2, verbose_name='Tipo de antecedente/alergia')),
                ('nombre_alergeno', models.CharField(blank=True, max_length=250, verbose_name='Nombre del alérgeno')),
                ('parentesco', models.CharField(blank=True, choices=[('01', 'Padres'), ('02', 'Hermanos'), ('03', 'Tíos'), ('04', 'Abuelos')], max_length=2)),
                ('diagnostico_familiar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antecedentes_familiares', to='catalogos.diagnostico')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='atencion.resultadovaloracion')),
            ],
            options={
                'verbose_name': 'Antecedente de salud',
                'verbose_name_plural': 'Antecedentes de salud',
                'db_table': 'ate_antecedente_salud',
                'ordering': ['tipo_alergia'],
            },
        ),
        migrations.CreateModel(
            name='TecnologiaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tecnologia', models.CharField(max_length=25, verbose_name='Código de la tecnología')),
                ('nombre_tecnologia', models.CharField(max_length=200, verbose_name='Nombre de la tecnología')),
                ('fecha_prescripcion', models.DateTimeField(blank=True, null=True)),
                ('dosis_prescrita', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('duracion_valor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración prescrita')),
                ('frecuencia_cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('dosis_administrada', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('dosis_entregada', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unidades_entregadas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='atencion.contactosalud')),
                ('descripcion_medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnologias', to='catalogos.descripcionmedicamento')),
                ('duracion_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duraciones', to='catalogos.unidadtiempo')),
                ('finalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tecnologias', to='catalogos.finalidadtecnologia')),
                ('frecuencia_unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frecuencias', to='catalogos.unidadtiempo')),
                ('talento_humano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnologias_aplicadas', to='catalogos.talentohumano')),
                ('tipo_tecnologia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tecnologias', to='catalogos.tipotecnologiasalud')),
                ('unidad_dosis_prescrita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosis_prescritas', to='catalogos.unidadmedida')),
                ('unidad_entregada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_entregadas', to='catalogos.unidadmedida')),
                ('via_administracion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnologias', to='catalogos.viaadministracion')),
            ],
            options={
                'verbose_name': 'Tecnología en salud',
                'verbose_name_plural': 'Tecnologías en salud',
                'db_table': 'ate_tecnologia_salud',
                'ordering': ['-fecha_prescripcion'],
            },
        ),
    ]
