# Generated by Django 6.0.5 on 2026-05-22 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('primer_nombre', models.CharField(max_length=60, verbose_name='Primer nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=60, verbose_name='Segundo nombre')),
                ('primer_apellido', models.CharField(max_length=60, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=60, verbose_name='Segundo apellido')),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='Fecha y hora de nacimiento')),
                ('sexo_biologico', models.CharField(choices=[('01', 'Hombre'), ('02', 'Mujer'), ('03', 'Indeterminado o Intersexual')], max_length=2, verbose_name='Sexo biológico')),
                ('identidad_genero', models.CharField(choices=[('01', 'Masculino'), ('02', 'Femenino'), ('03', 'Transgénero'), ('04', 'Neutro'), ('05', 'No lo declara')], max_length=2, verbose_name='Identidad de género')),
                ('zona_residencia', models.CharField(choices=[('01', 'Urbana'), ('02', 'Rural')], max_length=2, verbose_name='Zona de residencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('administradora_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_afiliados', to='catalogos.prestadorsalud', verbose_name='Administradora del plan de beneficios')),
                ('comunidad_etnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='catalogos.comunidadetnica')),
                ('etnia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='catalogos.etnia')),
                ('municipio_residencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='catalogos.municipio', verbose_name='Municipio de residencia')),
                ('ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='catalogos.ocupacion', verbose_name='Ocupación (CIUO-88)')),
                ('pais_residencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residentes', to='catalogos.pais', verbose_name='País de residencia habitual')),
                ('prestador_vinculacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_vinculados', to='catalogos.prestadorsalud', verbose_name='Prestador de vinculación')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='catalogos.tipodocumento', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pac_paciente',
                'ordering': ['primer_apellido', 'primer_nombre'],
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='OposicionDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifestacion', models.CharField(choices=[('01', 'Sí'), ('02', 'No')], help_text='01=Sí se opone, 02=No', max_length=2, verbose_name='Manifestación de oposición')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro del documento')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oposicion_donacion', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Oposición a donación',
                'verbose_name_plural': 'Oposiciones a donación',
                'db_table': 'pac_oposicion_donacion',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='VoluntadAnticipada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_documento', models.CharField(choices=[('01', 'Sí'), ('02', 'No')], max_length=2, verbose_name='¿Tiene documento de voluntad anticipada?')),
                ('fecha_documento', models.DateField(blank=True, null=True, verbose_name='Fecha de suscripción, modificación o revocación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntades_anticipadas', to='pacientes.paciente')),
                ('prestador_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntades_anticipadas', to='catalogos.prestadorsalud', verbose_name='Prestador donde reposa el documento')),
            ],
            options={
                'verbose_name': 'Voluntad anticipada',
                'verbose_name_plural': 'Voluntades anticipadas',
                'db_table': 'pac_voluntad_anticipada',
                'ordering': ['-fecha_documento'],
            },
        ),
        migrations.CreateModel(
            name='PacienteDiscapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='catalogos.discapacidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discapacidades', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Discapacidad del paciente',
                'verbose_name_plural': 'Discapacidades del paciente',
                'db_table': 'pac_discapacidad',
                'ordering': ['discapacidad__codigo'],
                'unique_together': {('paciente', 'discapacidad')},
            },
        ),
        migrations.CreateModel(
            name='PacienteNacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidades', to='pacientes.paciente')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nacionalidades_paciente', to='catalogos.pais')),
            ],
            options={
                'verbose_name': 'Nacionalidad del paciente',
                'verbose_name_plural': 'Nacionalidades del paciente',
                'db_table': 'pac_nacionalidad',
                'ordering': ['pais__nombre'],
                'unique_together': {('paciente', 'pais')},
            },
        ),
    ]
