# Generated by Django 6.0.5 on 2026-05-23 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_ocupacion_options_ocupacion_nivel_and_more'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacientenacionalidad',
            options={'ordering': ['pais__nombre'], 'verbose_name': 'País de la nacionalidad', 'verbose_name_plural': 'Países de nacionalidad del paciente'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='paises_nacionalidad',
            field=models.ManyToManyField(help_text='Res. 866: un paciente puede tener múltiples países de nacionalidad.', related_name='pacientes_por_nacionalidad', through='pacientes.PacienteNacionalidad', to='catalogos.pais', verbose_name='Países de nacionalidad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.ForeignKey(blank=True, help_text='Solo códigos de ocupación de 4 dígitos (nivel hoja CIUO-88).', limit_choices_to={'nivel': '5'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='catalogos.ocupacion', verbose_name='Ocupación al momento de la atención (CIUO-88)'),
        ),
        migrations.AlterField(
            model_name='pacientenacionalidad',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidades', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='pacientenacionalidad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nacionalidades_paciente', to='catalogos.pais', verbose_name='País de nacionalidad'),
        ),
    ]
