# Generated by Django 6.0.5 on 2026-05-23 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_ocupacion_options_ocupacion_nivel_and_more'),
        ('pacientes', '0002_alter_pacientenacionalidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ocupacion_otra',
            field=models.CharField(blank=True, help_text='Completar solo si la ocupación seleccionada es Otra.', max_length=250, verbose_name='Descripción de ocupación (Otra)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.ForeignKey(blank=True, help_text='Seleccione del catálogo CIUO-88 o la opción Otra (9999).', limit_choices_to={'nivel': '5'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='catalogos.ocupacion', verbose_name='Ocupación al momento de la atención (CIUO-88)'),
        ),
    ]
