# Generated by Django 6.0.5 on 2026-05-22 23:10

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CausaAtencion',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código causa')),
                ('nombre', models.CharField(max_length=200, verbose_name='Causa que motiva la atención')),
            ],
            options={
                'verbose_name': 'Causa de atención',
                'verbose_name_plural': 'Causas de atención',
                'db_table': 'cat_causa_atencion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('codigo', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Célula')),
            ],
            options={
                'verbose_name': 'Célula',
                'verbose_name_plural': 'Células',
                'db_table': 'cat_celula',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteSanguineo',
            fields=[
                ('codigo', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Componente sanguíneo')),
            ],
            options={
                'verbose_name': 'Componente sanguíneo',
                'verbose_name_plural': 'Componentes sanguíneos',
                'db_table': 'cat_componente_sanguineo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CondicionEgreso',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Condición de egreso')),
            ],
            options={
                'verbose_name': 'Condición de egreso',
                'verbose_name_plural': 'Condiciones de egreso',
                'db_table': 'cat_condicion_egreso',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DescripcionMedicamento',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código DCI')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Denominación común internacional')),
            ],
            options={
                'verbose_name': 'Descripción medicamento (DCI)',
                'verbose_name_plural': 'Descripciones de medicamentos',
                'db_table': 'cat_descripcion_medicamento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Discapacidad',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoría de discapacidad')),
            ],
            options={
                'verbose_name': 'Discapacidad',
                'verbose_name_plural': 'Discapacidades',
                'db_table': 'cat_discapacidad',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoMedico',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Dispositivo médico')),
            ],
            options={
                'verbose_name': 'Dispositivo médico',
                'verbose_name_plural': 'Dispositivos médicos',
                'db_table': 'cat_dispositivo_medico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EnfermedadHuerfana',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código enfermedad huérfana')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Enfermedad huérfana',
                'verbose_name_plural': 'Enfermedades huérfanas',
                'db_table': 'cat_enfermedad_huerfana',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código etnia')),
                ('nombre', models.CharField(max_length=100, verbose_name='Etnia')),
            ],
            options={
                'verbose_name': 'Etnia',
                'verbose_name_plural': 'Etnias',
                'db_table': 'cat_etnia',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FinalidadTecnologia',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código finalidad')),
                ('nombre', models.CharField(max_length=200, verbose_name='Finalidad')),
            ],
            options={
                'verbose_name': 'Finalidad de tecnología',
                'verbose_name_plural': 'Finalidades de tecnología',
                'db_table': 'cat_finalidad_tecnologia',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FluidoOrganico',
            fields=[
                ('codigo', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Fluido orgánico')),
            ],
            options={
                'verbose_name': 'Fluido orgánico',
                'verbose_name_plural': 'Fluidos orgánicos',
                'db_table': 'cat_fluido_organico',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentoMedicion',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Instrumento de medición')),
            ],
            options={
                'verbose_name': 'Instrumento de medición',
                'verbose_name_plural': 'Instrumentos de medición',
                'db_table': 'cat_instrumento_medicion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoConRegistro',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código IUM')),
                ('nombre', models.CharField(max_length=300, verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Medicamento con registro sanitario',
                'verbose_name_plural': 'Medicamentos con registro',
                'db_table': 'cat_medicamento_registro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoSinRegistro',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código UNIRS')),
                ('nombre', models.CharField(max_length=300, verbose_name='Medicamento sin registro (UNIRS)')),
            ],
            options={
                'verbose_name': 'Medicamento sin registro',
                'verbose_name_plural': 'Medicamentos sin registro',
                'db_table': 'cat_medicamento_sin_registro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoVital',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código IUM')),
                ('nombre', models.CharField(max_length=300, verbose_name='Medicamento vital no disponible')),
            ],
            options={
                'verbose_name': 'Medicamento vital no disponible',
                'verbose_name_plural': 'Medicamentos vitales no disponibles',
                'db_table': 'cat_medicamento_vital',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadTecnologia',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código modalidad')),
                ('nombre', models.CharField(max_length=150, verbose_name='Modalidad de realización')),
            ],
            options={
                'verbose_name': 'Modalidad de tecnología',
                'verbose_name_plural': 'Modalidades de tecnología',
                'db_table': 'cat_modalidad_tecnologia',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False, validators=[core.validators.validar_codigo_municipio], verbose_name='Código DIVIPOLA')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del municipio')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'cat_municipio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ocupacion',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código CIUO-88')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la ocupación')),
            ],
            options={
                'verbose_name': 'Ocupación',
                'verbose_name_plural': 'Ocupaciones (CIUO-88)',
                'db_table': 'cat_ocupacion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Organo',
            fields=[
                ('codigo', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Órgano')),
            ],
            options={
                'verbose_name': 'Órgano',
                'verbose_name_plural': 'Órganos',
                'db_table': 'cat_organo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[core.validators.validar_codigo_iso_pais], verbose_name='Código país (ISO 3166)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del país')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'cat_pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroResultado',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código parámetro')),
                ('nombre', models.CharField(max_length=200, verbose_name='Parámetro de resultado')),
            ],
            options={
                'verbose_name': 'Parámetro de resultado',
                'verbose_name_plural': 'Parámetros de resultado',
                'db_table': 'cat_parametro_resultado',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PreparacionMagistral',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Preparación magistral')),
            ],
            options={
                'verbose_name': 'Preparación magistral',
                'verbose_name_plural': 'Preparaciones magistrales',
                'db_table': 'cat_preparacion_magistral',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrestadorSalud',
            fields=[
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False, validators=[core.validators.validar_codigo_prestador], verbose_name='Código prestador SGSSS')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre de la entidad')),
                ('es_administradora', models.BooleanField(default=False, verbose_name='Es administradora de plan de beneficios')),
            ],
            options={
                'verbose_name': 'Prestador de salud',
                'verbose_name_plural': 'Prestadores de salud',
                'db_table': 'cat_prestador_salud',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código CUPS')),
                ('nombre', models.CharField(max_length=300, verbose_name='Procedimiento')),
            ],
            options={
                'verbose_name': 'Procedimiento (CUPS)',
                'verbose_name_plural': 'Procedimientos',
                'db_table': 'cat_procedimiento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProductoNutricional',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Producto nutricional')),
            ],
            options={
                'verbose_name': 'Producto nutricional',
                'verbose_name_plural': 'Productos nutricionales',
                'db_table': 'cat_producto_nutricional',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioComplementario',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Servicio complementario')),
            ],
            options={
                'verbose_name': 'Servicio complementario',
                'verbose_name_plural': 'Servicios complementarios',
                'db_table': 'cat_servicio_complementario',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tejido',
            fields=[
                ('codigo', models.CharField(max_length=19, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=300, verbose_name='Tejido')),
            ],
            options={
                'verbose_name': 'Tejido',
                'verbose_name_plural': 'Tejidos',
                'db_table': 'cat_tejido',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documento',
                'db_table': 'cat_tipo_documento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoTecnologiaSalud',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código tipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de tecnología en salud')),
            ],
            options={
                'verbose_name': 'Tipo de tecnología en salud',
                'verbose_name_plural': 'Tipos de tecnología en salud',
                'db_table': 'cat_tipo_tecnologia_salud',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código UMM')),
                ('nombre', models.CharField(max_length=100, verbose_name='Unidad')),
                ('tipo_unidad', models.CharField(blank=True, max_length=50, verbose_name='Tipo de unidad')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'cat_unidad_medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadTiempo',
            fields=[
                ('codigo', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Unidad de tiempo')),
            ],
            options={
                'verbose_name': 'Unidad de tiempo',
                'verbose_name_plural': 'Unidades de tiempo',
                'db_table': 'cat_unidad_tiempo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ViaAdministracion',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código VAD')),
                ('nombre', models.CharField(max_length=150, verbose_name='Vía de administración')),
            ],
            options={
                'verbose_name': 'Vía de administración',
                'verbose_name_plural': 'Vías de administración',
                'db_table': 'cat_via_administracion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ViaIngreso',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código vía de ingreso')),
                ('nombre', models.CharField(max_length=150, verbose_name='Vía de ingreso')),
            ],
            options={
                'verbose_name': 'Vía de ingreso',
                'verbose_name_plural': 'Vías de ingreso',
                'db_table': 'cat_via_ingreso',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Código CIE-10')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del diagnóstico')),
                ('enfermedad_huerfana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos', to='catalogos.enfermedadhuerfana')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos (CIE-10)',
                'db_table': 'cat_diagnostico',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ComunidadEtnica',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código comunidad')),
                ('nombre', models.CharField(max_length=200, verbose_name='Comunidad étnica')),
                ('etnia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comunidades', to='catalogos.etnia')),
            ],
            options={
                'verbose_name': 'Comunidad étnica',
                'verbose_name_plural': 'Comunidades étnicas',
                'db_table': 'cat_comunidad_etnica',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TalentoHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('nombres', models.CharField(blank=True, max_length=120, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=120, verbose_name='Apellidos')),
                ('registro_rethus', models.CharField(blank=True, max_length=20, verbose_name='Registro ReTHUS')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talentos_humanos', to='catalogos.tipodocumento')),
            ],
            options={
                'verbose_name': 'Talento humano en salud',
                'verbose_name_plural': 'Talento humano en salud',
                'db_table': 'cat_talento_humano',
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
    ]
