# Generated by Django 6.0.5 on 2026-05-23 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocupacion',
            options={'ordering': ['codigo'], 'verbose_name': 'Ocupación CIUO-88', 'verbose_name_plural': 'Ocupaciones CIUO-88 (jerárquicas)'},
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='nivel',
            field=models.CharField(choices=[('1', 'Gran grupo (1 dígito)'), ('2', 'Subgrupo mayor (2 dígitos)'), ('3', 'Subgrupo (3 dígitos)'), ('4', 'Grupo primario (4 dígitos)'), ('5', 'Ocupación (código de 4 dígitos — asignable al paciente)')], default='5', max_length=1, verbose_name='Nivel jerárquico CIUO-88'),
        ),
        migrations.AddField(
            model_name='ocupacion',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='catalogos.ocupacion', verbose_name='Nodo superior en la jerarquía'),
        ),
        migrations.AlterField(
            model_name='ocupacion',
            name='nombre',
            field=models.CharField(max_length=300, verbose_name='Nombre'),
        ),
    ]
